version: '3'
services:
  graphite-statsd:
    container_name: graphite-statsd
    image: graphiteapp/graphite-statsd
    volumes:
      - ./graphite-config/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
    ports:
      - 81:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
    environment:
      - GRAPHITE_TIME_ZONE=Europe/Istanbul